test_that("plot methods build without error", {
  d <- make_toy(n = 800); ax <- toy_axes()
  des <- survey::svydesign(id = ~psu, strata = ~strat, weights = ~w, data = d, nest = TRUE)
  g <- spec_fit(ax, d, des, exposure = c("x1", "x2"), marginal = FALSE)
  nul <- spec_null(g, scheme = "simple", reps = 1:4, stratum = "strat", seed = 9)
  def <- spec_defensible(nul, within = list(covset = "demo"))
  keep <- spec_keep(def, g)
  sm <- spec_summary(g, nul, keep = keep)
  vd <- spec_decompose(g, nul)
  p1 <- plot(g); p2 <- plot(g, keep = keep); p3 <- plot(def); p4 <- plot(sm, null = nul, keep = keep, grid = g); p5 <- plot(vd)
  for (p in list(p1, p2, p3, p4)) expect_s3_class(p, "ggplot")
  expect_s3_class(p5, "patchwork")
  for (p in list(p1, p2, p3, p4)) expect_no_error(ggplot2::ggplot_build(p))
  expect_no_error(print(p5))
  set.seed(1); dd <- data.frame(strat = rep(1:6, each = 100), psu = rep(1:2, 300), w = 1, x = stats::rlnorm(600))
  dd$y <- stats::rbinom(600, 1, stats::plogis(-1 + pmax(log2(dd$x), 0)))
  dz <- survey::svydesign(id = ~psu, strata = ~strat, weights = ~w, data = dd, nest = TRUE)
  bp <- breakpoint_boot(dd, dz, "x", "y", grid = c(0.1, 0.9, 9), B = 5, seed = 2)
  expect_s3_class(plot(bp), "ggplot")
})
