test_that("spec_decompose partitions variance, adds interactions, calibrates against a null and runs equal-cardinality draws", {
  d <- make_toy(n = 1200)
  ax <- spec_axes(outcome = c(any = "y_any", sev = "y_sev"), covariates = list(crude = character(0), demo = c("Age", "Gender")),
                  coding = c("per_sd", "log2", "q4_vs_q1"), sample = list(all = TRUE, age40 = quote(Age >= 40)), weighting = "unweighted")
  g <- spec_fit(ax, d, exposure = c("x1", "x2"), marginal = FALSE)
  v <- spec_decompose(g)
  expect_s3_class(v, "spec_decompose")
  expect_setequal(v$axes, c("outcome", "covset", "coding", "sample"))
  tot <- tapply(v$shares$share, v$shares$exposure, sum)
  expect_true(all(abs(tot - 1) < 1e-9))
  expect_true(all(abs(rowSums(v$main[, c(v$axes, "residual")]) - 1) < 1e-9))
  vi <- spec_decompose(g, interactions = TRUE)
  expect_true(all(c("pairwise", "higher_order") %in% names(vi$main)))
  expect_true(all(vi$main$pairwise >= 0 & vi$main$higher_order >= -1e-9))
  expect_equal(vi$main$outcome, v$main$outcome)        # main-effect shares unchanged by adding interactions (balanced grid)
  nul <- spec_null(g, scheme = "simple", reps = 1:6, stratum = "strat", seed = 2)
  vn <- spec_decompose(g, nul)
  expect_true(all(c("observed", "null_median", "null_q95", "p_perm") %in% names(vn$null)))
  expect_equal(nrow(vn$null), 2 * length(v$axes))
  expect_true(all(vn$null$p_perm >= 1 / 7 & vn$null$p_perm <= 1))
  ve <- spec_decompose(g, equal_cardinality = list(axis = "coding", k = 2))
  expect_equal(ve$equal_cardinality$n_draws, c(3, 3))
  expect_true(all(ve$equal_cardinality$prop_reduced_axis_largest >= 0 & ve$equal_cardinality$prop_reduced_axis_largest <= 1))
  expect_error(spec_decompose(g, equal_cardinality = list(axis = "coding", k = 3)), "smaller")
})
